apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: stg-cors@kubernetescrd
spec:
  ingressClassName: public
  rules:
    - host: api.stg.example.com
      http:
        paths:
          - {path: /, pathType: Prefix, backend: {service: {name: backend, port: {number: 8000}}}}
